// Realistic product data with real Unsplash images
export const MOCK_PRODUCTS = [
  {
    _id: 'p1',
    name: 'Handwoven Kashmiri Pashmina Shawl',
    description: 'Authentic hand-woven pashmina shawl from Kashmir, featuring intricate floral embroidery. Ultra-soft and lightweight, perfect for all seasons.',
    price: 2499,
    originalPrice: 4999,
    category: 'Fashion',
    images: [
      'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&q=80',
      'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400&q=80',
    ],
    rating: 4.8,
    numReviews: 234,
    stock: 18,
    sellerName: 'Rajwadi Fabrics',
    sellerVerified: true,
    tags: ['handmade', 'pashmina', 'kashmir', 'shawl'],
  },
  {
    _id: 'p2',
    name: 'Handcrafted Brass Diya Set (Set of 6)',
    description: 'Beautifully handcrafted brass diyas with intricate engravings. Perfect for festivals and home decoration. Comes in a premium gift box.',
    price: 849,
    originalPrice: 1299,
    category: 'Home Decor',
    images: [
      'https://images.unsplash.com/photo-1604598943838-5f0f71c1e4ad?w=400&q=80',
    ],
    rating: 4.9,
    numReviews: 567,
    stock: 45,
    sellerName: 'ArtisanCraft Co.',
    sellerVerified: true,
    tags: ['brass', 'diya', 'handcrafted', 'festive'],
  },
  {
    _id: 'p3',
    name: 'Rose Quartz & Pearl Layered Necklace',
    description: 'Elegant layered necklace with genuine rose quartz pendants and freshwater pearls. 18K gold-plated chain with adjustable length.',
    price: 1299,
    originalPrice: 2499,
    category: 'Jewellery',
    images: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&q=80',
    ],
    rating: 4.7,
    numReviews: 189,
    stock: 22,
    sellerName: 'Gems & Glory',
    sellerVerified: true,
    tags: ['necklace', 'rose-quartz', 'pearl', 'gold-plated'],
  },
  {
    _id: 'p4',
    name: 'Organic Saffron & Turmeric Face Cream',
    description: 'Luxurious face cream with pure Kashmiri saffron and organic turmeric. Brightens skin, reduces dark spots, and provides deep hydration. Paraben-free.',
    price: 699,
    originalPrice: 999,
    category: 'Beauty',
    images: [
      'https://images.unsplash.com/photo-1570194065650-d99fb4ee0bef?w=400&q=80',
    ],
    rating: 4.6,
    numReviews: 423,
    stock: 60,
    sellerName: 'Pure Botanics',
    sellerVerified: true,
    tags: ['organic', 'saffron', 'skincare', 'natural'],
  },
  {
    _id: 'p5',
    name: 'Hand-Block Printed Cotton Kurta',
    description: 'Premium hand-block printed cotton kurta from Jaipur artisans. Features traditional Rajasthani motifs. Available in S/M/L/XL.',
    price: 1199,
    originalPrice: 1899,
    category: 'Fashion',
    images: [
      'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=400&q=80',
    ],
    rating: 4.5,
    numReviews: 312,
    stock: 35,
    sellerName: 'Jaipur Threads',
    sellerVerified: true,
    tags: ['kurta', 'block-print', 'cotton', 'jaipur'],
  },
  {
    _id: 'p6',
    name: 'Terracotta Planter Set with Macramé Hanger',
    description: 'Set of 3 handcrafted terracotta planters with boho macramé hangers. Perfect for succulents and air plants. Includes drainage holes.',
    price: 599,
    originalPrice: 899,
    category: 'Home Decor',
    images: [
      'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400&q=80',
    ],
    rating: 4.7,
    numReviews: 201,
    stock: 40,
    sellerName: 'Earthy Vibes',
    sellerVerified: false,
    tags: ['terracotta', 'planter', 'macrame', 'boho'],
  },
  {
    _id: 'p7',
    name: 'Darjeeling First Flush Tea Caddy',
    description: 'Premium Darjeeling first flush tea in an elegant wooden caddy. Hand-picked from Makaibari Estate. 100g of artisan loose leaf tea.',
    price: 899,
    originalPrice: 1299,
    category: 'Food',
    images: [
      'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&q=80',
    ],
    rating: 4.9,
    numReviews: 678,
    stock: 80,
    sellerName: 'TeaTime India',
    sellerVerified: true,
    tags: ['tea', 'darjeeling', 'organic', 'premium'],
  },
  {
    _id: 'p8',
    name: 'Handmade Madhubani Painting — A4 Frame',
    description: 'Authentic Madhubani painting by Bihar artisans. Depicts traditional folk tales with natural dyes. Comes framed and ready to hang.',
    price: 1599,
    originalPrice: 2499,
    category: 'Art',
    images: [
      'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=400&q=80',
    ],
    rating: 4.8,
    numReviews: 145,
    stock: 12,
    sellerName: 'Folk Arts India',
    sellerVerified: true,
    tags: ['madhubani', 'painting', 'handmade', 'folk-art'],
  },
  {
    _id: 'p9',
    name: 'Ayurvedic Hair Oil — Brahmi & Amla Blend',
    description: 'Traditional Ayurvedic hair oil with cold-pressed brahmi and amla. Promotes hair growth, reduces hair fall, and nourishes scalp. 200ml.',
    price: 449,
    originalPrice: 699,
    category: 'Beauty',
    images: [
      'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&q=80',
    ],
    rating: 4.6,
    numReviews: 889,
    stock: 120,
    sellerName: 'Veda Naturals',
    sellerVerified: true,
    tags: ['ayurvedic', 'hair-oil', 'brahmi', 'amla'],
  },
  {
    _id: 'p10',
    name: 'Blue Pottery Chai Cup Set (Set of 4)',
    description: 'Authentic Jaipur blue pottery chai cups. Hand-painted with traditional floral motifs using natural dyes. Microwave safe.',
    price: 749,
    originalPrice: 1199,
    category: 'Home Decor',
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80',
    ],
    rating: 4.7,
    numReviews: 356,
    stock: 55,
    sellerName: 'Jaipur Pottery House',
    sellerVerified: false,
    tags: ['blue-pottery', 'chai', 'jaipur', 'handmade'],
  },
  {
    _id: 'p11',
    name: 'Emerald Kundan Bangles Set',
    description: 'Gorgeous kundan bangles with emerald-green stones in traditional Rajasthani setting. Set of 4 bangles, available in sizes 2.4, 2.6, 2.8.',
    price: 1899,
    originalPrice: 3499,
    category: 'Jewellery',
    images: [
      'https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=400&q=80',
    ],
    rating: 4.5,
    numReviews: 178,
    stock: 20,
    sellerName: 'Gems & Glory',
    sellerVerified: true,
    tags: ['kundan', 'bangles', 'emerald', 'rajasthani'],
  },
  {
    _id: 'p12',
    name: 'Organic Cold-Pressed Coconut Oil (500ml)',
    description: 'Pure organic coconut oil cold-pressed from fresh Kerala coconuts. Multi-use: cooking, hair care, and skin moisturizer. No additives.',
    price: 349,
    originalPrice: 499,
    category: 'Food',
    images: [
      'https://images.unsplash.com/photo-1526834718-dcc0d5fecc30?w=400&q=80',
    ],
    rating: 4.8,
    numReviews: 1234,
    stock: 200,
    sellerName: 'Kerala Organic Farm',
    sellerVerified: true,
    tags: ['coconut-oil', 'organic', 'cold-pressed', 'kerala'],
  },
]

export const MOCK_SELLERS = [
  {
    _id: 's1',
    name: 'Meera Sharma',
    sellerInfo: { storeName: 'Rajwadi Fabrics', storeTag: 'Premium Handlooms', rating: 4.9 },
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b332c91c?w=100&q=80',
    followers: [1, 2, 3, 4, 5, 6],
  },
  {
    _id: 's2',
    name: 'Arjun Mehta',
    sellerInfo: { storeName: 'ArtisanCraft Co.', storeTag: 'Handmade Décor', rating: 4.8 },
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    followers: [1, 2, 3],
  },
  {
    _id: 's3',
    name: 'Priya Nair',
    sellerInfo: { storeName: 'Pure Botanics', storeTag: 'Organic Beauty', rating: 4.7 },
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    followers: [1, 2, 3, 4, 5, 6, 7, 8],
  },
]

export const MOCK_LIVE_SESSIONS = [
  {
    _id: 'l1',
    title: 'Exclusive Festive Collection Launch 🎉',
    seller: { name: 'Meera Sharma', sellerInfo: { storeName: 'Rajwadi Fabrics', storeTag: 'Premium Handlooms', rating: 4.9 } },
    viewers: 2847,
    thumbnail: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=80',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    category: 'Fashion',
    products: [MOCK_PRODUCTS[0], MOCK_PRODUCTS[4]],
    isLive: true,
  },
  {
    _id: 'l2',
    title: 'Diwali Décor Haul — Live Unboxing',
    seller: { name: 'Arjun Mehta', sellerInfo: { storeName: 'ArtisanCraft Co.', storeTag: 'Handmade Décor', rating: 4.8 } },
    viewers: 1203,
    thumbnail: 'https://images.unsplash.com/photo-1604598943838-5f0f71c1e4ad?w=600&q=80',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    category: 'Home Decor',
    products: [MOCK_PRODUCTS[1], MOCK_PRODUCTS[5]],
    isLive: true,
  },
  {
    _id: 'l3',
    title: 'Skincare Routine with Pure Botanics',
    seller: { name: 'Priya Nair', sellerInfo: { storeName: 'Pure Botanics', storeTag: 'Organic Beauty', rating: 4.7 } },
    viewers: 876,
    thumbnail: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    category: 'Beauty',
    products: [MOCK_PRODUCTS[3], MOCK_PRODUCTS[8]],
    isLive: true,
  },
]

export const CHAT_NAMES = ['Priya', 'Rahul', 'Meena', 'Arjun', 'Sunita', 'Vikram', 'Ananya', 'Rohan', 'Divya', 'Karan']
export const CHAT_MSGS = [
  'How much for bulk order?', 'Is COD available?', '🔥🔥🔥', 'Love this!',
  'Shipping to Mumbai?', 'Just ordered! 🎉', 'Quality looks amazing', '😍 So beautiful',
  'Any discount for first order?', 'Size M available?', 'Great seller! Already bought twice',
]
